### ISSUE TITLE
I don't understand what you're doing here. Can you please explain

### ISSUE THREAD

**Issue by RCinbo** [RCinbo/IPBESValueAssessment#1]
https://github.com/RCinbo/IPBESValueAssessment/blob/531a33f7b3167664bf2cd9e8031106ddb2e96a00/read%20responses.R#L23

**Comment by hrlee1202** [comment]
Hello

**Comment by hrlee1202** [comment]
Hello Raisa,

Can you please make me as a contributor to the repository? I could not list it in my Github account.
It would be much easier for me to list it

Thanks!
Heera


—————

Dr. Heera Lee
Postdoctoral fellow
Land Use Change Research Group
Institute of Meteorology and Climate Research (IMK-IFU)
Karlsruhe Institute of Technology (KIT)

Kreuzeckbahnstrasse 19
82467 Garmisch-Partenkirchen
Germany
www.imk-ifu.kit.edu<http://www.imk-ifu.kit.edu>

On 25. Sep 2020, at 14:59, raisa_carmen <notifications@github.com<mailto:notifications@github.com>> wrote:



Assigned #1<https://github.com/RCinbo/IPBESValueAssessment/issues/1> to @hrlee1202<https://github.com/hrlee1202>.
