### ISSUE TITLE
Merge ?

### ISSUE THREAD

**Issue by hrlee1202** [RCinbo/IPBESValueAssessment#12]
Hello!
Each time I upload a file and then revise again (and push), I always have a problem with 'merge'. The first time Push is fine (when I upload a new file), and then I revise and push, doesn't work.. I deleted one file and want to revise it with another one, but could not do.. Can you please help me?

**Comment by hrlee1202** [comment]
Oh I guess, it is somehow resolved if you can see the file 'Step1_table_Oct2020.R' ?

**Comment by RCinbo** [comment]
Hmmm, are you sure you're still working on the master branch? 
A merge commonly occurs when you want to push a branch to the master.
