### ISSUE TITLE
include one observation from repeated ones (test phase + reliability repititions)

### ISSUE THREAD

**Issue by Sander-Jacobs** [RCinbo/IPBESValueAssessment#13]

**Comment by hrlee1202** [comment]
Test phase studies --> See the other issue regarding the number of rows to exclude.

17 rows are included to the 's3_single'. I call the final data as s3_single, so you don't need to change your code to run. 
There are 4 studies ID multiply found in Step 2 table, but not in Step 3 table (21, 1752, 8708, 46344). They are not included.

**Comment by hrlee1202** [comment]
so I think the final data is ready (including the repeated ones). So please update your figures!
