### ISSUE TITLE
check papers with #methods > 4

### ISSUE THREAD

**Issue by Sander-Jacobs** [RCinbo/IPBESValueAssessment#14]
heera extracts paper ID, Sander to screen

**Comment by hrlee1202** [comment]
Hello, why did you close this Issue? @Sander-Jacobs 

i extracted Paper ID of 28 papers that have more than 4 methods per application. (based on the question 1.1) 
These are the Paper IDs. if you have further question, please let me know! 

21402 17191 72614 32152 70939 76572  6392  6653 37789 23505 23840 12597
25474 41326 46198 43798 34045 22904 42028 41028 10573 33318 39778 43876 43876 43876 38445 64683

**Comment by Sander-Jacobs** [comment]
Hi heera, i accidentally closed it...

Sorry...

**Comment by Sander-Jacobs** [comment]
it is done!! 
I have recounted the methods here: 
https://docs.google.com/spreadsheets/d/1OGrZYQMkmJ6OESortI40Dhs6LITLQGb7zS0GRZ3Fg_w/edit#gid=0

**Comment by hrlee1202** [comment]
Thanks! Will try to correct the data based on your correction.

**Comment by hrlee1202** [comment]
@Sander-Jacobs 
https://docs.google.com/spreadsheets/d/1OGrZYQMkmJ6OESortI40Dhs6LITLQGb7zS0GRZ3Fg_w/edit#gid=0
paper ID: 22904
Is it correct that this study has 13 methods? Initially, it was 11..

**Comment by hrlee1202** [comment]
For the Additional Method (1.3.)

-- The number of additional methods > 4
-- paper ID:
38316 38518 17191 29506 74437 17155 58559 26512 29915 10261  4714 36263
 8869  3206 35757 34150 69884 54436 20791 59670 23700 35913 62947 44894
2198  9727 23185 45593 28465 43314 42378 39619 12597  3734 71934  2248
22816 41028 14021 16915  6493 25781 25094  6674 20245 38947 66234 69734
 20317  7586
