### ISSUE TITLE
Adding keyword-based method families to the s3_single dataframe

### ISSUE THREAD

**Issue by RCinbo** [RCinbo/IPBESValueAssessment#17]
I tried to add the keyword search method families from the step 1 table to the s3_single dataframe (find the code through the link below). I'm unsure with which variable from the step 1 table I can match the s3_single$paperID. I thought is would be data.final$TSU.ID_MERGED but that variable apparently runs from 2 to 79041 while the paperID runs from 1 to 77470.

What is the best way to combine step 1 and 3 table?

https://github.com/RCinbo/IPBESValueAssessment/blob/19d10894623e463a01e6858bee15e2a2e5eeef51/Starting.R#L127-L135

**Comment by hrlee1202** [comment]
Oh that's right.. now I remember that TSU wanted it to start with '2' so it can match with the row number in Excel (the first row is the head). And this ID has been the ID that we communicated with TSU and students (I believe?). When I sampled the papers from the Step 1 table, I gave the TSU.ID to TSU to collect the corresponding papers and I believe these have been delivered to students?

**Comment by hrlee1202** [comment]
I am not sure then why s3_single doesn't match..

**Comment by hrlee1202** [comment]
It turned out that these are the testing papers and others seem to match with the Step 1 table. We decided to exclude those testing papers from the Step 2 and Step 3 tables.
