### ISSUE TITLE
Step 1 table

### ISSUE THREAD

**Issue by hrlee1202** [RCinbo/IPBESValueAssessment#7]
The Step 1 table is too large to upload it to Github. If it is not necessary for everyone to work on Step 1 table, I can handle it whenever needed. Otherwise, I can upload it to Google Drive and read the table from there..?

**Comment by RCinbo** [comment]
I've made a local folder called 'data' in the director where I keep the IPBES Rproject on my computer. If you open de .gitignore text document, you'll see that this folder wil be ignored when synching with github. Using google drive is certainly possible but this does mean that you'll have to upload it to google drive each time a new version exists.

Another solution which can ensure that all of us can work with the last, most up-to-date version of Step 1 (as long as the code is up-to-date) could be the following:

if (!file.exists('./data/DATANAME.Rda')){
 put your code here to create the Table1 cleaned up table and save it to "DATANAME.Rda" in the data folder. Whenever you delete "DATANAME.Rda" in the data folder, a new version will automatically be created when you run your code.
}

**Comment by hrlee1202** [comment]
Oh, I forgot to mention that Step 1 table does not change. It stays as it is until the end. It is the complete list of the (found) studies where we sampled randomly based on method families and regions for Step 2 and Step 3. A data folder sounds good, too. I am afraid that I haven't got the second line of your comment (Sorry, my Github experience is still limited). We can discuss it further tomorrow!
